"""Aesthetic Color Grading, Sharpness, and Motion Profiles."""

PRESETS = {
    "tiktok_4k_120fps": {
        "name": "TikTok 4K 120 FPS (Laggy Viral Edit)",
        "description": "The signature high-bitrate TikTok edit: 4K 120 FPS, H.264 High Profile, 75 Mbps, razor CAS 0.75 clarity, subtle bloom, and vibrant S-curve HDR.",
        "cas_strength": 0.75,
        "unsharp_luma": 1.2,
        "unsharp_chroma": 0.8,
        "denoise_luma": 1.5,
        "denoise_chroma": 3.0,
        "saturation": 1.25,
        "contrast": 1.16,
        "brightness": 0.01,
        "gamma": 0.97,
        "bloom_enabled": True,
        "bloom_threshold": 0.72,
        "bloom_blur": 14.0,
        "bloom_opacity": 0.24,
        "s_curve": "0/0 0.22/0.17 0.50/0.50 0.78/0.85 1/1",
        "motion_mode": "blend",
        "default_fps": 120,
        "default_resolution": "4k",
        "codec": "h264",
        "bitrate_mbps": 75,
    },
    "instagram_reels_hdr": {
        "name": "Instagram Reels 4K 60 FPS (Ultra HDR Pop)",
        "description": "Vivid saturated colors, crystal micro-contrast, warm edge glow, and vibrant skin tones optimized for Instagram feeds.",
        "cas_strength": 0.80,
        "unsharp_luma": 1.3,
        "unsharp_chroma": 0.9,
        "denoise_luma": 1.4,
        "denoise_chroma": 2.8,
        "saturation": 1.32,
        "contrast": 1.20,
        "brightness": 0.01,
        "gamma": 0.96,
        "bloom_enabled": True,
        "bloom_threshold": 0.70,
        "bloom_blur": 15.0,
        "bloom_opacity": 0.25,
        "s_curve": "0/0 0.20/0.15 0.50/0.50 0.80/0.88 1/1",
        "color_balance": {"rs": 0.02, "gs": 0.01, "bs": -0.01, "rh": 0.03, "gh": 0.01, "bh": -0.02},
        "motion_mode": "mci",
        "default_fps": 60,
        "default_resolution": "4k",
        "codec": "h264",
        "bitrate_mbps": 65,
    },
    "low_light_indoor_fix": {
        "name": "Indoor & Night Video Savior (Bus / Night Fix)",
        "description": "Engineered for dark rooms, night footage, and bus interiors: heavy noise suppression, lifted shadow gamma, and protected highlights to prevent blown-out lamps.",
        "cas_strength": 0.60,
        "unsharp_luma": 0.9,
        "unsharp_chroma": 0.5,
        "denoise_luma": 2.6,
        "denoise_chroma": 4.5,
        "saturation": 1.15,
        "contrast": 1.08,
        "brightness": 0.02,
        "gamma": 1.05,
        "bloom_enabled": True,
        "bloom_threshold": 0.84,
        "bloom_blur": 10.0,
        "bloom_opacity": 0.16,
        "s_curve": "0/0 0.26/0.24 0.50/0.52 0.76/0.80 1/1",
        "motion_mode": "blend",
        "default_fps": 60,
        "default_resolution": "4k",
        "codec": "h264",
        "bitrate_mbps": 65,
    },
    "velocity_flow_480fps": {
        "name": "Velocity Flow 480 FPS (Liquid Motion Blur)",
        "description": "Liquid smooth high-shutter motion with 480 FPS temporal blending, clean optical blur, and razor clarity.",
        "cas_strength": 0.70,
        "unsharp_luma": 1.1,
        "unsharp_chroma": 0.7,
        "denoise_luma": 1.8,
        "denoise_chroma": 3.5,
        "saturation": 1.20,
        "contrast": 1.14,
        "brightness": 0.00,
        "gamma": 0.98,
        "bloom_enabled": True,
        "bloom_threshold": 0.72,
        "bloom_blur": 12.0,
        "bloom_opacity": 0.20,
        "s_curve": "0/0 0.24/0.19 0.50/0.50 0.76/0.83 1/1",
        "motion_mode": "blend",
        "default_fps": 480,
        "default_resolution": "4k",
        "codec": "h264",
        "bitrate_mbps": 80,
    },
    "youtube_shorts_8k": {
        "name": "YouTube Shorts 8K Master (True Clarity)",
        "description": "True 8K (4320x7680) studio upscaling with 95 Mbps master bitrate, zero artificial grain, and maximum fine detail.",
        "cas_strength": 0.55,
        "unsharp_luma": 0.8,
        "unsharp_chroma": 0.5,
        "denoise_luma": 1.2,
        "denoise_chroma": 2.2,
        "saturation": 1.12,
        "contrast": 1.10,
        "brightness": 0.00,
        "gamma": 1.00,
        "bloom_enabled": False,
        "bloom_threshold": 0.80,
        "bloom_blur": 8.0,
        "bloom_opacity": 0.12,
        "s_curve": "0/0 0.25/0.22 0.50/0.50 0.75/0.80 1/1",
        "motion_mode": "blend",
        "default_fps": 60,
        "default_resolution": "8k",
        "codec": "h264",
        "bitrate_mbps": 95,
    },
    "viral_tiktok_hdr": {
        "name": "Viral TikTok HDR (Laggy 8K Aesthetic)",
        "description": "The signature viral edit look: deep S-curve contrast, glowing highlight bloom, razor CAS sharpness, and vivid HDR saturation.",
        "cas_strength": 0.75,
        "unsharp_luma": 1.2,
        "unsharp_chroma": 0.8,
        "denoise_luma": 1.5,
        "denoise_chroma": 3.0,
        "saturation": 1.25,
        "contrast": 1.18,
        "brightness": 0.01,
        "gamma": 0.96,
        "bloom_enabled": True,
        "bloom_threshold": 0.70,
        "bloom_blur": 15.0,
        "bloom_opacity": 0.26,
        "s_curve": "0/0 0.22/0.16 0.50/0.50 0.78/0.86 1/1",
        "motion_mode": "mci",
        "default_fps": 60,
        "default_resolution": "4k",
        "codec": "h264",
        "bitrate_mbps": 65,
    },
    "velocity_flow_60fps": {
        "name": "Velocity Flow (Smooth 60 FPS Flow)",
        "description": "Liquid smooth motion with natural high-shutter motion blur, clean optical flow, and crisp edge clarity.",
        "cas_strength": 0.65,
        "unsharp_luma": 1.0,
        "unsharp_chroma": 0.6,
        "denoise_luma": 1.8,
        "denoise_chroma": 3.5,
        "saturation": 1.18,
        "contrast": 1.12,
        "brightness": 0.00,
        "gamma": 0.98,
        "bloom_enabled": True,
        "bloom_threshold": 0.70,
        "bloom_blur": 12.0,
        "bloom_opacity": 0.20,
        "s_curve": "0/0 0.25/0.20 0.50/0.50 0.75/0.82 1/1",
        "motion_mode": "blend",
        "default_fps": 60,
        "default_resolution": "4k",
        "codec": "h264",
        "bitrate_mbps": 55,
    },
    "alight_motion_dark": {
        "name": "Alight Motion Dark Aesthetic CC",
        "description": "Moody, aggressive crushed blacks, high-contrast neon edges, and punchy pop. Favored by anime & phonk editors.",
        "cas_strength": 0.85,
        "unsharp_luma": 1.4,
        "unsharp_chroma": 0.9,
        "denoise_luma": 1.2,
        "denoise_chroma": 2.5,
        "saturation": 1.35,
        "contrast": 1.25,
        "brightness": -0.02,
        "gamma": 0.92,
        "bloom_enabled": True,
        "bloom_threshold": 0.60,
        "bloom_blur": 18.0,
        "bloom_opacity": 0.35,
        "s_curve": "0/0 0.18/0.10 0.50/0.48 0.82/0.92 1/1",
        "motion_mode": "mci",
        "default_fps": 60,
        "default_resolution": "4k",
        "codec": "h264",
        "bitrate_mbps": 60,
    },
    "cyberpunk_neon": {
        "name": "Cyberpunk Neon & Cold Glow",
        "description": "Deep cyan shadows, warm amber highlights, high-frequency edge isolation, and strong specular glow.",
        "cas_strength": 0.90,
        "unsharp_luma": 1.5,
        "unsharp_chroma": 1.0,
        "denoise_luma": 1.5,
        "denoise_chroma": 3.0,
        "saturation": 1.30,
        "contrast": 1.22,
        "brightness": 0.01,
        "gamma": 0.95,
        "bloom_enabled": True,
        "bloom_threshold": 0.58,
        "bloom_blur": 22.0,
        "bloom_opacity": 0.38,
        "s_curve": "0/0 0.20/0.14 0.50/0.50 0.80/0.90 1/1",
        "color_balance": {"rs": -0.05, "gs": 0.02, "bs": 0.08, "rh": 0.08, "gh": 0.02, "bh": -0.06},
        "motion_mode": "mci",
        "default_fps": 60,
        "default_resolution": "4k",
        "codec": "h264",
        "bitrate_mbps": 65,
    },
    "raw_master_8k": {
        "name": "Raw Master 8K (Pristine True Clarity)",
        "description": "Studio-grade optical upscaling with zero artificial over-saturation. True 8K / 4K fidelity and master bitrate.",
        "cas_strength": 0.50,
        "unsharp_luma": 0.7,
        "unsharp_chroma": 0.4,
        "denoise_luma": 1.0,
        "denoise_chroma": 2.0,
        "saturation": 1.08,
        "contrast": 1.06,
        "brightness": 0.00,
        "gamma": 1.00,
        "bloom_enabled": False,
        "bloom_threshold": 0.75,
        "bloom_blur": 10.0,
        "bloom_opacity": 0.15,
        "s_curve": "0/0 0.25/0.23 0.50/0.50 0.75/0.78 1/1",
        "motion_mode": "blend",
        "default_fps": 60,
        "default_resolution": "8k",
        "codec": "h264",
        "bitrate_mbps": 80,
    },
    "extreme_phone_killer_12k": {
        "name": "12K Extreme Phone Killer (Benchmark Master)",
        "description": "The absolute peak: 12K Extreme Resolution (74.6 Megapixels/frame), 120 Mbps master bitrate, razor CAS 0.92, glowing bloom. (Requires Workstation GPU / Benchmark only).",
        "cas_strength": 0.92,
        "unsharp_luma": 1.6,
        "unsharp_chroma": 1.0,
        "denoise_luma": 1.2,
        "denoise_chroma": 2.5,
        "saturation": 1.35,
        "contrast": 1.25,
        "brightness": 0.01,
        "gamma": 0.94,
        "bloom_enabled": True,
        "bloom_threshold": 0.62,
        "bloom_blur": 25.0,
        "bloom_opacity": 0.40,
        "s_curve": "0/0 0.18/0.12 0.50/0.50 0.82/0.92 1/1",
        "motion_mode": "blend",
        "default_fps": 60,
        "default_resolution": "12k",
        "codec": "h265",
        "bitrate_mbps": 120,
    },
}

RESOLUTIONS = {
    "1080p": {"width": 1080, "height": 1920, "label": "Full HD (1080 x 1920)"},
    "2k": {"width": 1440, "height": 2560, "label": "2K QHD (1440 x 2560)"},
    "4k": {"width": 2160, "height": 3840, "label": "4K Ultra HD (2160 x 3840)"},
    "8k": {"width": 4320, "height": 7680, "label": "8K Master (4320 x 7680)"},
    "12k": {"width": 6480, "height": 11520, "label": "12K Extreme Master (6480 x 11520)"},
}

def get_preset(name: str) -> dict:
    """Return preset configuration dictionary with fallback."""
    return PRESETS.get(name.lower(), PRESETS["viral_tiktok_hdr"]).copy()
